version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  redis:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  elasticsearch:
    driver: ${VOLUMES_DRIVER}

services:

  php:
    build:
      context: docker/php
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${PHP_INI_OVERRIDE_PATH}:/usr/local/etc/php/conf.d/php-ini-override.ini
      - ${PHP_SUPERVISORD_PATH}:/etc/supervisor/supervisor.d
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    environment:
      - APPLICATION_ENV=${APPLICATION_ENV}
    networks:
      - backend

  node:
    build:
      context: docker/node
      args:
        - NODE_VERSION=${NODE_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    networks:
      - backend

  nginx:
    build:
      context: docker/nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_VHOSTS_PATH}:/etc/nginx/vhosts
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d
      - ${NGINX_SNIPPETS_PATH}:/etc/nginx/snippets
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php
    networks:
      - frontend
      - backend

  mariadb:
    build: docker/mariadb
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend

  redis:
    build: docker/redis
    networks:
      - backend
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  elasticsearch:
    build: docker/elasticsearch
    volumes:
      - ${DATA_PATH_HOST}/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=hive-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ELASTICSEARCH_MAX_MEMORY_SIZE} -Xmx${ELASTICSEARCH_MAX_MEMORY_SIZE}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    networks:
      - frontend
      - backend

  kibana:
    build: docker/kibana
    ports:
      - "${KIBANA_HTTP_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - frontend
      - backend